class NotificationType {
  // NOTIFICATION TYPE
  static const String NOTIFICATION_TYPE_LIKE = "NOTIFICATION_LIKE";
  static const String NOTIFICATION_TYPE_COMMENT = "NOTIFICATION_COMMENT";
  static const String NOTIFICATION_TYPE_REPOST = "NOTIFICATION_REPOST";
  static const String NOTIFICATION_TYPE_MESSAGE = "NOTIFICATION_MESSAGE";
  static const String NOTIFICATION_TYPE_FOLLOW = "NOTIFICATION_FOLLOW";
  static const String NOTIFICATION_TYPE_MENTION = "NOTIFICATION_MENTION";
  static const String NOTIFICATION_TYPE_BERITA = "NOTIFICATION_BERITA";
  static const String NOTIFICATION_TYPE_BUKU_SAKU = "NOTIFICATION_BUKU_SAKU";
  static const String NOTIFICATION_TYPE_BUKU_PANDUAN =
      "NOTIFICATION_BUKU_PANDUAN";
  static const String NOTIFICATION_TYPE_ELEARNING = "NOTIFICATION_ELEARNING";
  static const String NOTIFICATION_KEGIATAN_DELETED =
      "NOTIFICATION_KEGIATAN_DELETED";
  static const String NOTIFICATION_KEGIATAN_UPDATED =
      "NOTIFICATION_KEGIATAN_UPDATED";

  static const String NOTIFICATION_TKK = "NOTIFICATION_TKK";
  static const String NOTIFICATION_TKU = "NOTIFICATION_TKU";
  static const String NOTIFICATION_TKK_NEED_APPROVE =
      "NOTIFICATION_TKK_NEED_APPROVE";
  static const String NOTIFICATION_TKU_NEED_APPROVE =
      "NOTIFICATION_TKU_NEED_APPROVE";

  static const String NOTIFICATION_PENGHARGAAN = "NOTIFICATION_PENGHARGAAN";
  static const String NOTIFICATION_KEGIATAN = "NOTIFICATION_KEGIATAN";
  static const String NOTIFICATION_PENGHARGAAN_NEED_APPROV =
      "NOTIFICATION_PENGHARGAAN_NEED_APPROVE";
  static const String NOTIFICATION_KEGIATAN_NEED_APPROV =
      "NOTIFICATION_KEGIATAN_NEED_APPROVE";

  static const String NOTIFICATION_ABSENSI_CHECKIN =
      "NOTIFICATION_ABSENSI_CHECKIN";
  static const String NOTIFICATION_ABSENSI_CHECKOUT =
      "NOTIFICATION_ABSENSI_CHECKOUT";
}
